# Stage 1: Build the application with Maven
FROM maven:3.9.5-eclipse-temurin-17 as build

# Set working directory
WORKDIR /app

# Copy source code and build the application
COPY . .

# Maven code compilation
RUN mvn clean package -DskipTests

# Stage 2: Create lightweight final image
FROM eclipse-temurin:17.0.14_7-jre-alpine-3.21

# Create a user and provide permissions to myuser to /app directory only
RUN mkdir /app && adduser -D myuser && chown -R myuser /app

# Switch user to myuser
USER myuser

# Set working directory
WORKDIR /app

# Copy only the JAR from the previous build stage
COPY --from=build /app/target/*.jar app.jar

# Run the JAR
ENTRYPOINT ["java", "-jar", "app.jar"]